# CLOMonitor chart default configuration values

imagePullSecrets: []
imageTag: ""
nameOverride: ""
pullPolicy: IfNotPresent

# Enable dynamic resource name prefix
#
# Enabling the dynamic resource name prefix ensures that the resources are named dynamically based on the Helm
# installation's name. This allows multiple installations of this chart in a single Kubernetes namespace. The prefix
# can be defined by using the `fullnameOverride`.
dynamicResourceNamePrefixEnabled: false

# Overwrites the installation's fullname generation (used for the dynamic resource name prefix)
fullnameOverride: ""

# Directory path where the configuration files should be mounted
configDir: "/home/clomonitor/.config/clomonitor"

# Check database readiness init container configuration
checkDbIsReadyInitContainer:
  securityContext: {}

# Database configuration
db:
  host: ""
  port: "5432"
  dbname: clomonitor
  user: clomonitor
  password: clomonitor

# Credentials
creds:
  githubTokens: []
  notifierGithubToken: null

# Log configuration
log:
  # Output format [json|pretty]
  format: json

# Database migrator configuration
dbmigrator:
  job:
    containerSecurityContext: {}
    image:
      # Database migrator image repository (without the tag)
      repository: clomonitor/dbmigrator
    podSecurityContext: {}

# API server configuration
apiserver:
  # Address to listen on
  addr: 0.0.0.0:8000
  # Base URL
  baseURL: http://localhost:8000
  # Path with static assets
  staticPath: /home/clomonitor/web/build
  basicAuth:
    # Enable basic auth
    enabled: false
    # Basic auth username
    username: clomonitor
    # Basic auth password
    password: changeme
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    backendServicePort: 80
    rules: []
    tls: []
  service:
    allocateLoadBalancerNodePorts: true
    annotations: {}
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8000
    type: NodePort
  deploy:
    containerSecurityContext: {}
    image:
      # API server image repository (without the tag)
      repository: clomonitor/apiserver
    podSecurityContext: {}
    readinessProbe:
      httpGet:
        path: /
        port: 8000
    replicaCount: 1
    resources: {}

# Archiver configuration
archiver:
  cronjob:
    containerSecurityContext: {}
    image:
      # Archiver image repository (without the tag)
      repository: clomonitor/archiver
    podSecurityContext: {}
    resources: {}

# Notifier configuration
notifier:
  enabled: false
  cronjob:
    containerSecurityContext: {}
    image:
      # Notifier image repository (without the tag)
      repository: clomonitor/notifier
    podSecurityContext: {}
    resources: {}

# Registrar configuration
registrar:
  cronjob:
    containerSecurityContext: {}
    image:
      # Registrar image repository (without the tag)
      repository: clomonitor/registrar
    podSecurityContext: {}
    resources: {}
  # Number of foundations to process concurrently
  concurrency: 1

# Tracker configuration
tracker:
  cronjob:
    containerSecurityContext: {}
    image:
      # Tracker image repository (without the tag)
      repository: clomonitor/tracker
    podSecurityContext: {}
    resources: {}
  # Number of repositories to process concurrently
  # The number of tokens defined in creds.githubTokens must be equal or greater
  # than the concurrency value, otherwise the concurrency will be limited to
  # the number of tokens available.
  concurrency: 10

# Values for postgresql chart dependency
postgresql:
  enabled: true
  auth:
    database: clomonitor
    password: clomonitor
    username: clomonitor
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: artifacthub/postgres
    tag: latest
  persistence:
    mountPath: /data
  primary:
    extraVolumes:
      - name: run
        emptyDir: {}
    extraVolumeMounts:
      - name: run
        mountPath: /var/run/postgresql
